security:
 oauth2:
   client:
     clientId: ${SAF_CLIENT_ID}
     clientSecret: ${SAF_CLIENT_SECRET}
     accessTokenUri: ${SAF_RETRIEVE_TOKEN_PATH:https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/token}
     userAuthorizationUri: ${SAF_AUTH_PATH:https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/oauth2/authorize}
     tokenName: oauth_token
     authenticationScheme: query
     clientAuthenticationScheme: form
     scope: ${SAF_SCOPE:basicprofile,racfid}
   resource:
      userInfoUri: ${SAF_VALIDATE_TOKEN_PATH:https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/41/auth/userinfo?scopes=basicprofile.racfid}
spring:
      datasource:
          driver-class-name: com.ibm.db2.jcc.DB2Driver
          url: ${DB_CMS_JDBC_URL:jdbc:db2://192.168.99.100:50000/DB0TDEV}
          username: ${DB_CMS_USER:db2inst1}
          password: ${DB_CMS_PASSWORD:db2inst1}
      jpa:
          database: db2
          show_sql: true
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
              hibernate.ddl-auto: none
              hibernate.default_schema: ${DB_CMS_SCHEMA:CWSINT}
perry:
    identityProvider:
      idpMapping: 'config/idp.groovy'
    jwt:
      timeout: ${TOKEN_TIMEOUT:30} #minutes
      issuer: ${TOKEN_ISSUER:perry}
      encryptionEnabled: ${TOKEN_ENCRYPTION_ENABLED:true}
      encryptionMethod: ${TOKEN_ENCRYPTION_METHOD:A256GCM}
      headless: ${HEADLESS_JWT:true}
      keyStore:
        path: ${KEYSTORE_PATH:config/enc.jceks}
        alias: ${KEYSTORE_ALIAS:test}
        password: ${KEYSTORE_PASSWORD:test}
        keyPassword : ${KEYSTORE_KEY_PASSWORD:test}
        encAlias:  ${KEYSTORE_ENC_ALIAS:enc}
        encKeyPassword: ${KEYSTORE_ENC_KEY_PASSWORD:test}
    serviceProviders:
      default:
        identityMapping: 'config/default.groovy'

server:
  context-path: ${CONTEXT_PATH:/}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  port: ${HTTPS_PORT:8090}
  ssl:
    enabled: true
    keyStoreType: JCEKS
    trustStoreType: JCEKS
    keyStore: ${KEYSTORE_PATH:config/enc.jceks}
    keyStorePassword: ${KEYSTORE_PASSWORD:test}
    keyPassword: ${KEYSTORE_KEY_PASSWORD:test}
  http:
    port: ${HTTP_PORT:8080}