spring:
      datasource:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:test
          username: test
          password: test
      jpa:
          database: h2
          show_sql: ${SHOW_SQL:false}
          hibernate:
              ddl-auto: create
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
      redis:
          host: ${REDIS_HOST:192.168.99.100}
          password: ${REDIS_PASSWORD:}
          port: ${REDIS_PORT:6379}

perry:
    identityManager:
          idmMapping: ${IDM_MAPPING_SCRIPT:config/idm.groovy}
          idmBasicAuthUser: ${IDM_BASIC_AUTH_USER:}
          idmBasicAuthPass: ${IDM_BASIC_AUTH_PASSWORD:}
    jwt:
      timeout: ${TOKEN_TIMEOUT:10} #minutes
      issuer: ${TOKEN_ISSUER:perry}
      encryptionEnabled: ${TOKEN_ENCRYPTION_ENABLED:true}
      encryptionMethod: ${TOKEN_ENCRYPTION_METHOD:A128GCM}
      headless: ${HEADLESS_JWT:true}
      keyStore:
        path: ${KEYSTORE_PATH:config/enc.jceks}
        alias: ${KEYSTORE_ALIAS:test}
        password: ${KEYSTORE_PASSWORD:test}
        keyPassword : ${KEYSTORE_KEY_PASSWORD:test}
        encAlias:  ${KEYSTORE_ENC_ALIAS:enc128}
        encKeyPassword: ${KEYSTORE_ENC_KEY_PASSWORD:test}
    tokenStore:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:token_store
        username:
        password:
      jpa:
        database: h2
        show_sql: true
        hibernate:
           ddl-auto: none
        properties:
           hibernate.cache.use_query_cache: false
           hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
           hibernate.dialect: org.hibernate.dialect.H2Dialect
           hibernate.default_schema:
    serviceProviders:
      default:
        identityMapping: config/dev.groovy
    users: ${USERS:}
    whiteList: ${WHITE_LIST:*}
    homePageUrl: ${HOME_PAGE_URL:/}
    showErrors: ${SHOW_ERRORS:true}
    tokenRecordTimeout: ${TOKEN_RECORD_TIMEOUT:7} # days
    liquibase:
      schema:
        change-log: classpath:/liquibase/perry_schema.xml
      structure:
        change-log: classpath:/liquibase/perry_database_master.xml
management:
  context-path: /manage
  port: ${ADMIN_PORT:9082}
  security:
    enabled: false
  ssl:
    enabled: false
  endpoints:
    enabled: false
    health:
      enabled: true
    info:
      enabled: false
    env:
      enabled: false
    configprops:
      enabled: false
server:
  context-path: ${CONTEXT_PATH:/perry}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  port: ${HTTPS_PORT:8090}
  ssl:
    enabled: ${SSL_ENABLED:false}
    keyStoreType: JCEKS
    trustStoreType: JCEKS
    keyStore: ${KEYSTORE_PATH:config/enc.jceks}
    keyStorePassword: ${KEYSTORE_PASSWORD:test}
    keyPassword: ${KEYSTORE_KEY_PASSWORD:test}
  http:
    port: ${HTTP_PORT:8080}
  error:
    whitelabel:
      enabled: false
cognito:
  iamAccessKeyId: ${COGNITO_IAM_ACCESS_ID:}
  iamSecretKey: ${COGNITO_IAM_SECRET:}
  region: ${COGNITO_REGION:us-east-2}
  userpool: ${COGNITO_USERPOOL:us-east-2_Hp5BRwwOJ}
logging:
  file: ${LOG_FILE:perry-log.txt}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
        security: ${LOG_LEVEL:DEBUG}
      hibernate: ${LOG_LEVEL:DEBUG}
search:
  doraUrl: ${DORA_URL:https://dora.preint.cwds.io}
  index: ${ES_USER_INDEX:users}
  type: ${ES_USER_TYPE:user}
