spring:
      datasource:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:test
          username: test
          password: test
      jpa:
          database: h2
          show_sql: true
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
              hibernate.ddl-auto: none
              hibernate.default_schema: test
perry:
    jwt:
      timeout: ${TOKEN_TIMEOUT:30} #minutes
      issuer: ${TOKEN_ISSUER:perry}
      encryptionEnabled: ${TOKEN_ENCRYPTION_ENABLED:true}
      encryptionMethod: ${TOKEN_ENCRYPTION_METHOD:A128GCM}
      headless: ${HEADLESS_JWT:true}
      keyStore:
        path: ${KEYSTORE_PATH:config/enc.jceks}
        alias: ${KEYSTORE_ALIAS:test}
        password: ${KEYSTORE_PASSWORD:test}
        keyPassword : ${KEYSTORE_KEY_PASSWORD:test}
        encAlias:  ${KEYSTORE_ENC_ALIAS:enc128}
        encKeyPassword: ${KEYSTORE_ENC_KEY_PASSWORD:test}
    serviceProviders:
      default:
        identityMapping: 'config/default.groovy'
    #users:
    #  userid: password

server:
  context-path: ${CONTEXT_PATH:/}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  port: ${HTTPS_PORT:8090}
  ssl:
    enabled: true
    keyStoreType: JCEKS
    trustStoreType: JCEKS
    keyStore: ${KEYSTORE_PATH:config/enc.jceks}
    keyStorePassword: ${KEYSTORE_PASSWORD:test}
    keyPassword: ${KEYSTORE_KEY_PASSWORD:test}
  http:
    port: ${HTTP_PORT:8080}