applicationName: Perry
version: ${APP_VERSION:-local}
loginResourceHelper: gov.ca.cwds.rest.resources.auth.SimpleAccountLoginResourceHelper

saf:
  baseUrl: ${SAF_BASE_URL:-https://sectest.dss.ca.gov/web1/dss_saf}
  authPath: ${SAF_AUTH_PATH:-/auth/v2/oauth2/authorize}
  retrieveTokenPath: ${SAF_RETRIEVE_TOKEN_PATH:-/auth/v2/token}
  validateTokenPath: ${SAF_VALIDATE_TOKEN_PATH:-/data/v2/api/client/41/auth/validatetoken}
  clientId: ${SAF_CLIENT_ID:-XXXXXX}
  clientSecret: ${SAF_CLIENT_SECRET:-XXXXXX}
  callbackUrl: ${SAF_CALLBACK_URL:-http://localhost:8090/authn/callback}
  scope: ${SAF_SCOPE:-basic_profile}

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro.ini}"]

jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true

simpleAccountLogin:
  templateName: simpleAccountLogin.mustache
  assetsPath: /static 

swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS API
  description: RESTful API definitions for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png

server:
  applicationConnectors:
  - type: http 
    port: ${APP_STD_PORT:-8090}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8091}
    
  requestLog:
    appenders:
      - type: console

logging:
  level: ${LOGLEVEL:-DEBUG}
  loggers:
    "org.hibernate.SQL":
      level: ALL
    "org.hibernate.type.descriptor.sql":
      level: ALL
    "AUDIT":
      level: ALL
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: '%d %level %X{remoteAddress} [%thread] %logger{0}: userid:"%X{userid}" sessionid:"%X{sessionid}" uniqueId:="%X{uniqueId}" "%message%n"'  
