security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
  #oauth2:
  #  client:
  #    clientId: XXX
  #    clientSecret: XXX
  #    accessTokenUri: https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/token
  #    userAuthorizationUri: https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/oauth2/authorize
  #    tokenName: oauth_token
  #    authenticationScheme: query
  #    clientAuthenticationScheme: form
  #    pre-established-redirect-uri: http://54.70.247.41/cwds/callback
  #    registered-redirect-uri: http://54.70.247.41/cwds/callback
  #    use-current-uri: false
  #    scope: basic_profile
  #  resource:
  #      userInfoUri: https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/41/auth/validatetoken
spring:
      datasource:
          driver-class-name: com.ibm.db2.jcc.DB2Driver
          url: jdbc:db2://192.168.99.100:50000/DB0TDEV
          #name: CWSINT
          username: db2inst1
          password: db2inst1
      jpa:
          database: db2
          show_sql: true
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
              hibernate.ddl-auto: none
              hibernate.default_schema: CWSINT
perry:
    jwt:
      timeout: 30 #minutes
      issuer: perry
    keyStore:
      path: config/test.jks
      alias: test
      password: test
      keyPassword : test
    saf:
      userInfoUrl: https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/41/auth/validatetoken
    serviceProviders:
        dora:
          identityMapping: 'config/dora.groovy'
flyway:
  enabled: false