security:
 oauth2:
   client:
     clientId: ${SAF_CLIENT_ID:aa0415d3-779f-4be4-ac3e-43fb1a596d76}
     clientSecret: ${SAF_CLIENT_SECRET:AM2Z3iiEWwwqjzXi1ShMviac4N/INdbxsgm6V1lrw2db2CAT1KizYFtTsPfkXzPAZnyPey1CkPk3ChHz+k6Jo+d6e/kagcbQXW0xSB/MDJUf1Wp/QOzLB3CJjumfe5rHAE7YSJn+9M3dJJUS6bv36WjH/FhrKGrjlP5fl12FYmZFWXFiTMLaXHy8DSW8JnD7MptGkoxtD/9VhPB/C7Y5SVLiUpxXB8eQ+EC4lYXENTAVsZvey6xFCrnV79fi4KhTTsrLVR4kJ0wkOYX8uJn3z/kaIOUupF9kkuQfvhClp4zgXIQDNZ0nsreYmcl3eAF9dFjk2ux6BppvCOEzoTFqQQ==}
     accessTokenUri: ${SAF_RETRIEVE_TOKEN_PATH:https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/token}
     userAuthorizationUri: ${SAF_AUTH_PATH:https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/oauth2/authorize}
     tokenName: ${TOKEN_NAME:oauth_token}
     authenticationScheme: ${SAF_AUTH_SCHEME:header}
     clientAuthenticationScheme: ${SAF_CLIENT_AUTH_SCHEME:form}
     scope: ${SAF_SCOPE:basicprofile,racfid}
     useCurrentUri: ${USE_CURRENT_URI:true}
     preEstablishedRedirectUri: ${REDIRECT_URI:http://localhost:8080/perry}
   resource:
     userInfoUri: ${SAF_USER_INFO_URI:https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/43/auth/userinfo?scopes=basicprofile.racfid}
     tokenInfoUri: ${SAF_VALIDATE_TOKEN_URI:https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/43/auth/validatetoken}
     revokeTokenUri: ${SAF_REVOKE_TOKEN_URI:https://sectest.dss.ca.gov/web1/dss_saf/data/v2/api/client/43/auth/revoketoken}
     logoutTokenUri: ${SAF_LOGOUT_URI:https://sectest.dss.ca.gov/web1/dss_saf/auth/v2/client/43/oauth2/logout}
spring:
      datasource:
          driver-class-name: com.ibm.db2.jcc.DB2Driver
          url: ${DB_CMS_JDBC_URL:jdbc:db2://localhost:50000/DB0TDEV}
          username: ${DB_CMS_USER:db2inst1}
          password: ${DB_CMS_PASSWORD:db2inst1-pwd}
          testOnBorrow: ${DB_CMS_TEST_ON_BORROW:true}
          testWhileIdle: ${DB_CMS_TEST_WHILE_IDLE:true}
          validationQuery: select 1 from ${spring.jpa.properties.hibernate.default_schema}.userid_t fetch first 1 row only with ur
          logValidationErrors: ${DB_CMS_LOG_VALIDATION_ERRORS:false}
      jpa:
          database: db2
          show_sql: ${SHOW_SQL:false}
          hibernate:
              ddl-auto: none
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
              hibernate.default_schema: ${DB_CMS_SCHEMA:CWSCMSRS}
      redis:
          host: ${REDIS_HOST:192.168.99.100}
          password: ${REDIS_PASSWORD:}
          port: ${REDIS_PORT:6379}

perry:
    identityProvider:
      idpMapping: ${IDP_MAPPING_SCRIPT:config/idp.groovy}
    jwt:
      timeout: ${TOKEN_TIMEOUT:10} #minutes
      issuer: ${TOKEN_ISSUER:perry}
      encryptionEnabled: ${TOKEN_ENCRYPTION_ENABLED:true}
      encryptionMethod: ${TOKEN_ENCRYPTION_METHOD:A256GCM}
      headless: ${HEADLESS_JWT:true}
      keyStore:
        path: ${KEYSTORE_PATH:config/enc.jceks}
        alias: ${KEYSTORE_ALIAS:test}
        password: ${KEYSTORE_PASSWORD:test}
        keyPassword : ${KEYSTORE_KEY_PASSWORD:test}
        encAlias:  ${KEYSTORE_ENC_ALIAS:enc}
        encKeyPassword: ${KEYSTORE_ENC_KEY_PASSWORD:test}
    serviceProviders:
      default:
        identityMapping: ${SP_IDENTITY_MAPPING_SCRIPT:config/default.groovy}
      intake:
        identityMapping: ${SP_INTAKE_IDENTITY_MAPPING_SCRIPT:config/intake.groovy}
    whiteList: ${WHITE_LIST:*} # urls separated by spaces.
    homePageUrl: ${HOME_PAGE_URL:/}
    showErrors: ${SHOW_ERRORS:true}
    tokenRecordTimeout: ${TOKEN_RECORD_TIMEOUT:7} # days
    tokenStore:
        datasource:
            driver-class-name: org.postgresql.Driver
            url: ${TOKEN_STORE_JDBC_URL:jdbc:postgresql://postgres.preint02.cwds.io:5432/postgres}
            username: ${TOKEN_STORE_DB_USER:postgres}
            password: ${TOKEN_STORE_DB_PASSWORD:postgres}
            testOnBorrow: ${TOKEN_STORE_TEST_ON_BORROW:true}
            testWhileIdle: ${TOKEN_STORE_TEST_WHILE_IDLE:true}
            validationQuery: select 1
            logValidationErrors: ${TOKEN_STORE_LOG_VALIDATION_ERRORS:false}
        jpa:
           database: POSTGRESQL
           show_sql: true
           hibernate:
              ddl-auto: none
           properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.ProgressDialect
              hibernate.default_schema: ${TOKEN_STORE_SCHEMA:perry}
    liquibase:
        schema:
            change-log: classpath:/liquibase/perry_schema.xml
            default-schema: public
        structure:
            change-log: classpath:/liquibase/perry_database_master.xml
            default-schema: perry
management:
  context-path: /manage
  port: ${ADMIN_PORT:9082}
  security:
    enabled: false
  ssl:
    enabled: false
  endpoints:
    enabled: false
    health:
      enabled: true
    info:
      enabled: false
    env:
      enabled: false
    configprops:
      enabled: false
server:
  context-path: ${CONTEXT_PATH:/perry}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  port: ${HTTPS_PORT:8090}
  ssl:
    enabled: ${SSL_ENABLED:false}
    keyStoreType: JCEKS
    trustStoreType: JCEKS
    keyStore: ${KEYSTORE_PATH:config/enc.jceks}
    keyStorePassword: ${KEYSTORE_PASSWORD:test}
    keyPassword: ${KEYSTORE_KEY_PASSWORD:test}
  http:
    port: ${HTTP_PORT:8080}
  error:
    whitelabel:
      enabled: false
logging:
  file: ${LOG_FILE:perry-log.txt}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    gov.ca.cwds.config.logging: ${LOG_LEVEL:DEBUG}
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
        security: ${LOG_LEVEL:DEBUG}
      hibernate: ${LOG_LEVEL:DEBUG}
