security:
 oauth2:
   client:
     clientId: 770f4f66-5bb5-4300-b673-0aa1a46b3ee2
     clientSecret: e42bdf1b-afb8-4dd4-a7ef-8ff8008945a7
     accessTokenUri: ${SAF_RETRIEVE_TOKEN_PATH:http://localhost:9081/identity-provider/oauth/token}
     userAuthorizationUri: ${SAF_AUTH_PATH:http://localhost:9081/identity-provider/oauth/authorize}
     tokenName: oauth_token
     authenticationScheme: query
     clientAuthenticationScheme: header
     scope: read
   resource:
      userInfoUri: ${SAF_USER_INFO_URI:http://localhost:9081/identity-provider/resource/me}
      tokenInfoUri: ${SAF_VALIDATE_TOKEN_URI:http://localhost:9081/identity-provider/resource/validatetoken}
spring:
      datasource:
          driver-class-name: com.ibm.db2.jcc.DB2Driver
          url: ${DB_CMS_JDBC_URL:jdbc:db2://192.168.99.100:50000/DB0TDEV}
          username: ${DB_CMS_USER:db2inst1}
          password: ${DB_CMS_PASSWORD:db2inst1}
      jpa:
          database: db2
          show_sql: ${SHOW_SQL:false}
          properties:
              hibernate.cache.use_query_cache: false
              hibernate.current_session_context_class : org.springframework.orm.hibernate5.SpringSessionContext
              hibernate.dialect: org.hibernate.dialect.DB2Dialect
              hibernate.ddl-auto: none
              hibernate.default_schema: ${DB_CMS_SCHEMA:CWSCMS}
perry:
    identityProvider:
      idpMapping: 'config/idp-preview.groovy'
    jwt:
      timeout: ${TOKEN_TIMEOUT:30} #minutes
      issuer: ${TOKEN_ISSUER:perry}
      encryptionEnabled: ${TOKEN_ENCRYPTION_ENABLED:true}
      encryptionMethod: ${TOKEN_ENCRYPTION_METHOD:A128GCM}
      headless: ${HEADLESS_JWT:true}
      keyStore:
        path: ${KEYSTORE_PATH:config/enc.jceks}
        alias: ${KEYSTORE_ALIAS:test}
        password: ${KEYSTORE_PASSWORD:test}
        keyPassword : ${KEYSTORE_KEY_PASSWORD:test}
        encAlias:  ${KEYSTORE_ENC_ALIAS:enc128}
        encKeyPassword: ${KEYSTORE_ENC_KEY_PASSWORD:test}
    serviceProviders:
      default:
        identityMapping: 'config/default-preview.groovy'
    whiteList: ${WHITE_LIST:*} # urls separated by spaces.
management:
  context-path: /manage
  port: ${ADMIN_PORT:9082}
  security:
    enabled: false
  ssl:
    enabled: false
endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: false
  env:
    enabled: false
  configprops:
    enabled: false
server:
  context-path: ${CONTEXT_PATH:/perry}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  port: ${HTTPS_PORT:8090}
  ssl:
    enabled: true
    keyStoreType: JCEKS
    trustStoreType: JCEKS
    keyStore: ${KEYSTORE_PATH:config/enc.jceks}
    keyStorePassword: ${KEYSTORE_PASSWORD:test}
    keyPassword: ${KEYSTORE_KEY_PASSWORD:test}
  http:
    port: ${HTTP_PORT:8080}
  error:
    whitelabel:
      enabled: false
logging:
  file: ${LOG_FILE:perry-log.txt}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:DEBUG}
        security: ${LOG_LEVEL:DEBUG}
      hibernate: ${LOG_LEVEL:DEBUG}